"""Steering file generation for AI tools."""

from pathlib import Path
from collections import defaultdict
from typing import List


STEERING_TARGETS = [
    ("kiro",    ".kiro/steering",  "knowledge-graph.md",      True),
    ("cursor",  ".cursor/rules",   "knowledge-graph.md",      True),
    ("copilot", ".github",         "copilot-instructions.md", True),
    ("claude",  ".",               "CLAUDE.md",               False),
    ("windsurf",".",               ".windsurfrules",          False),
    ("cline",   ".",               ".clinerules",             False),
    ("codex",   ".",               "AGENTS.md",               False),
]

TOOL_NAMES = [t[0] for t in STEERING_TARGETS]


def _build_steering_content(graph_data: dict) -> str:
    p = graph_data["project"]
    layers_summary = "\n".join(f"- **{l['name']}**: {len(l['node_ids'])} nodes" for l in graph_data["layers"])
    node_counts = defaultdict(int)
    for n in graph_data["nodes"]: node_counts[n["type"]] += 1
    stats = ", ".join(f"{c} {t}s" for t, c in sorted(node_counts.items(), key=lambda x: -x[1]))

    top_nodes = sorted(
        [n for n in graph_data["nodes"] if n["type"] in ("class","function") and n.get("complexity") != "simple"],
        key=lambda n: (0 if n["type"]=="class" else 1, 0 if n.get("complexity")=="complex" else 1))[:30]
    top_ref = "\n".join(f"- `{n['name']}` ({n['type']}, {n.get('complexity','')}) in `{n.get('file_path','')}`" for n in top_nodes)

    return f"""# Codebase Knowledge Graph

Auto-generated by SteerCode. Re-run `python steercode.py .` to update.

## Project: {p['name']}
- Languages: {', '.join(p.get('languages', []))}
- {stats}
- Knowledge graph: `.codemap-output/knowledge-graph.json`

## Architectural Layers
{layers_summary}

## Key Nodes
{top_ref}

## Instructions for AI

### Before modifying code
1. Read `.codemap-output/knowledge-graph.json` — it maps every file, function, class, and their relationships
2. Find the target node, then trace its edges to understand dependencies
3. Check the `layers` array to understand which architectural layer you're working in

### Knowledge Graph Schema
- `nodes[]`: id, type (file|function|class), name, file_path, line_range, summary, complexity
- `edges[]`: source → target, type (imports|contains|calls|inherits)
- `layers[]`: id (api|ui|service|data|infra|test|docs), node_ids[]

### Impact analysis
To find what changing function X affects: find node X → follow outgoing "calls"/"imports" edges → list affected nodes.
"""


def generate_steering(graph_data: dict, root: Path, output_dir: Path, tools: List[str] = None) -> List[str]:
    """Generate steering files for selected AI tools (all if tools is None)."""
    content = _build_steering_content(graph_data)
    paths = []
    selected = [t for t in STEERING_TARGETS if tools is None or t[0] in tools]

    for name, dir_rel, filename, auto in selected:
        if auto:
            target_dir = root / dir_rel
            target_dir.mkdir(parents=True, exist_ok=True)
            (target_dir / filename).write_text(content, encoding="utf-8")
            paths.append(str((target_dir / filename).relative_to(root)))
        else:
            steering_dir = output_dir / "steering"
            steering_dir.mkdir(parents=True, exist_ok=True)
            (steering_dir / filename).write_text(content, encoding="utf-8")
            paths.append(str((steering_dir / filename).relative_to(root) if steering_dir.is_relative_to(root) else steering_dir / filename))

    return paths
