import json
from pathlib import Path
from collections import defaultdict
from typing import List

def _strip_defaults(graph_data: dict) -> dict:
    """Remove empty/default fields to reduce JSON size."""
    stripped = {**graph_data}
    stripped["nodes"] = []
    for n in graph_data["nodes"]:
        node = {k: v for k, v in n.items()
                if v and v != [] and v != (0, 0) and v != [0, 0] and v != "simple"}
        # Keep complexity only if not simple
        if n.get("complexity") and n["complexity"] != "simple":
            node["complexity"] = n["complexity"]
        stripped["nodes"].append(node)
    stripped["edges"] = []
    for e in graph_data["edges"]:
        edge = {"source": e["source"], "target": e["target"], "type": e["type"]}
        if e.get("weight", 0.5) != 0.5: edge["weight"] = e["weight"]
        stripped["edges"].append(edge)
    return stripped

def generate_dashboard(graph_data: dict, output_dir: Path):
    template_path = Path(__file__).parent.parent / "dashboard_template.html"
    template = template_path.read_text(encoding="utf-8")
    output_dir.mkdir(parents=True, exist_ok=True)

    compact = _strip_defaults(graph_data)

    # Compact JSON for machines
    kg_path = output_dir / "knowledge-graph.json"
    kg_path.write_text(json.dumps(compact, ensure_ascii=False, separators=(",", ":")), encoding="utf-8")

    # Dashboard data
    graph_json = json.dumps(graph_data, ensure_ascii=False, separators=(",", ":"))
    (output_dir / "data.js").write_text(f"const GRAPH_DATA={graph_json};", encoding="utf-8")

    html = template.replace("const GRAPH_DATA = {{GRAPH_JSON}};", "/* data loaded from data.js */")
    html = html.replace("{{PROJECT_NAME}}", graph_data["project"]["name"])
    dash_path = output_dir / "dashboard.html"
    dash_path.write_text(html, encoding="utf-8")

    return dash_path, kg_path

def _build_steering_content(graph_data: dict) -> str:
    """Build steering markdown content (shared across all AI tools)."""
    p = graph_data["project"]
    layers_summary = "\n".join(f"- **{l['name']}**: {len(l['node_ids'])} nodes" for l in graph_data["layers"])
    node_counts = defaultdict(int)
    for n in graph_data["nodes"]: node_counts[n["type"]] += 1
    stats = ", ".join(f"{c} {t}s" for t, c in sorted(node_counts.items(), key=lambda x: -x[1]))

    top_nodes = sorted(
        [n for n in graph_data["nodes"] if n["type"] in ("class","function") and n.get("complexity") != "simple"],
        key=lambda n: (0 if n["type"]=="class" else 1, 0 if n.get("complexity")=="complex" else 1))[:30]
    top_ref = "\n".join(f"- `{n['name']}` ({n['type']}, {n.get('complexity','')}) in `{n.get('file_path','')}`" for n in top_nodes)

    return f"""# Codebase Knowledge Graph

Auto-generated by SteerCode. Re-run `python steercode.py .` to update.

## Project: {p['name']}
- Languages: {', '.join(p.get('languages', []))}
- {stats}
- Knowledge graph: `.codemap-output/knowledge-graph.json`

## Architectural Layers
{layers_summary}

## Key Nodes
{top_ref}

## Instructions for AI

### Before modifying code
1. Read `.codemap-output/knowledge-graph.json` — it maps every file, function, class, and their relationships
2. Find the target node, then trace its edges to understand dependencies
3. Check the `layers` array to understand which architectural layer you're working in

### Knowledge Graph Schema
- `nodes[]`: id, type (file|function|class), name, file_path, line_range, summary, complexity
- `edges[]`: source → target, type (imports|contains|calls|inherits)
- `layers[]`: id (api|ui|service|data|infra|test|docs), node_ids[]

### Impact analysis
To find what changing function X affects: find node X → follow outgoing "calls"/"imports" edges → list affected nodes.
"""

# Steering targets: (dir, filename, auto-place)
# auto-place=True: generate directly (subdirectory tools)
# auto-place=False: generate in .codemap-output/steering/ (root-level tools)
STEERING_TARGETS = [
    (".kiro/steering",  "knowledge-graph.md",    True),   # Kiro
    (".cursor/rules",   "knowledge-graph.md",    True),   # Cursor
    (".github",         "copilot-instructions.md", True), # GitHub Copilot
    (".",               "CLAUDE.md",             False),   # Claude Code
    (".",               ".windsurfrules",        False),   # Windsurf
    (".",               ".clinerules",           False),   # Cline
    (".",               "AGENTS.md",             False),   # Codex
]

def generate_steering(graph_data: dict, root: Path, output_dir: Path) -> List[str]:
    """Generate steering files for all supported AI tools."""
    content = _build_steering_content(graph_data)
    paths = []

    # Subdirectory tools — place directly
    for dir_rel, filename, auto in STEERING_TARGETS:
        if auto:
            target_dir = root / dir_rel
            target_dir.mkdir(parents=True, exist_ok=True)
            (target_dir / filename).write_text(content, encoding="utf-8")
            paths.append(str((target_dir / filename).relative_to(root)))

    # Root-level tools — collect in .codemap-output/steering/
    steering_dir = output_dir / "steering"
    steering_dir.mkdir(parents=True, exist_ok=True)
    for dir_rel, filename, auto in STEERING_TARGETS:
        if not auto:
            (steering_dir / filename).write_text(content, encoding="utf-8")

    paths.append(f"{output_dir.relative_to(root)}/steering/ (CLAUDE.md, AGENTS.md, ...)")
    return paths
    return path
