"""Onboarding guide generator — create docs/ONBOARDING.md from knowledge graph."""

from pathlib import Path
from collections import defaultdict
from typing import Optional


def generate_onboard(graph_data: dict, root: Path, output: str = "docs/ONBOARDING.md") -> str:
    """Generate onboarding markdown from graph data. Returns file path."""
    p = graph_data["project"]
    nodes = graph_data["nodes"]
    layers = graph_data.get("layers", [])

    sections = [f"# {p['name']} — Onboarding Guide\n", f"Auto-generated by SteerCode.\n"]

    # Overview table
    node_counts = defaultdict(int)
    for n in nodes: node_counts[n["type"]] += 1
    versions = p.get("versions", {})
    fw = ", ".join(f"{k} {v}" for k, v in versions.get("frameworks", {}).items()) or "—"
    sections.append(f"""
## Overview

| Metric | Value |
|---|---|
| Languages | {', '.join(p.get('languages', [])[:8])} |
| Files | {node_counts.get('file', 0):,} |
| Functions | {node_counts.get('function', 0):,} |
| Classes | {node_counts.get('class', 0):,} |
| Frameworks | {fw} |
""")

    # Architecture layers
    if layers:
        sections.append("## Architecture\n")
        for l in sorted(layers, key=lambda x: -len(x["node_ids"])):
            sections.append(f"- **{l['name']}** ({len(l['node_ids']):,} nodes)")
        sections.append("")

    # Key components by importance
    scored = [n for n in nodes if n["type"] in ("function", "class")
              and (n.get("semantics", {}).get("importance") or n.get("importance", 0))]
    scored.sort(key=lambda n: n.get("semantics", {}).get("importance", 0) or n.get("importance", 0), reverse=True)
    if scored:
        sections.append("\n## Key Components\n")
        for n in scored[:20]:
            sem = n.get("semantics", {})
            parts = [f"`{n['name']}`", f"({n['type']})"]
            role = sem.get("execution_role", "") or n.get("role", "")
            domain = sem.get("domain_hint", "") or n.get("domain", "")
            effects = [e.get("type", e) if isinstance(e, dict) else e for e in (sem.get("side_effects", []) or n.get("effects", []))]
            if role: parts.append(role)
            if domain: parts.append(f"[{domain}]")
            if effects: parts.append("→ " + ", ".join(effects[:3]))
            parts.append(f"in `{n.get('file_path', '')}`")
            sections.append(f"- {' · '.join(parts)}")
        sections.append("")

    # Complexity hotspots
    complex_nodes = [n for n in nodes if n.get("complexity") == "complex" and n["type"] in ("function", "class")]
    complex_nodes.sort(key=lambda n: (n.get("line_range", [0, 0])[1] - n.get("line_range", [0, 0])[0]), reverse=True)
    if complex_nodes:
        sections.append("\n## Complexity Hotspots\n")
        for n in complex_nodes[:15]:
            lr = n.get("line_range", [0, 0])
            lines = lr[1] - lr[0] + 1 if lr[1] > lr[0] else 0
            sections.append(f"- `{n['name']}` ({lines} lines) in `{n.get('file_path', '')}`")
        sections.append("")

    # Reading order by layer dependency
    layer_order = ["Data / Storage", "Service / Logic", "API / Routes", "UI / Frontend", "Infrastructure", "Tests"]
    ordered = [l for lo in layer_order for l in layers if l["name"] == lo]
    if ordered:
        sections.append("\n## Recommended Reading Order\n")
        for i, l in enumerate(ordered, 1):
            file_nodes = [n for n in nodes if n["id"] in set(l["node_ids"]) and n["type"] == "file"]
            dirs = sorted(set(str(Path(n["file_path"]).parent) for n in file_nodes[:50]))[:5]
            sections.append(f"{i}. **{l['name']}** — {', '.join(dirs) if dirs else 'various'}")
        sections.append("")

    # Write
    content = "\n".join(sections)
    out_path = root / output
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(content, encoding="utf-8")
    return str(out_path.relative_to(root))
