"""Onboarding guide generator — create docs/ONBOARDING.md from knowledge graph."""

from pathlib import Path
from collections import defaultdict
from typing import Optional


def generate_onboard(graph_data: dict, root: Path, output: str = "docs/ONBOARDING.md") -> str:
    """Generate onboarding markdown from graph data. Returns file path."""
    p = graph_data["project"]
    nodes = graph_data["nodes"]
    edges = graph_data.get("edges", [])
    layers = graph_data.get("layers", [])

    sections = [f"# {p['name']} — Onboarding Guide\n", f"Auto-generated by SteerCode.\n"]

    # Overview table
    node_counts = defaultdict(int)
    for n in nodes: node_counts[n["type"]] += 1
    versions = p.get("versions", {})
    fw = ", ".join(f"{k} {v}" for k, v in versions.get("frameworks", {}).items()) or "—"
    sections.append(f"""
## Overview

| Metric | Value |
|---|---|
| Languages | {', '.join(p.get('languages', [])[:8])} |
| Files | {node_counts.get('file', 0):,} |
| Functions | {node_counts.get('function', 0):,} |
| Classes | {node_counts.get('class', 0):,} |
| Frameworks | {fw} |
""")

    # Architecture layers
    if layers:
        sections.append("## Architecture\n")
        for l in sorted(layers, key=lambda x: -len(x["node_ids"])):
            sections.append(f"- **{l['name']}** ({len(l['node_ids']):,} nodes)")
        sections.append("")

    # Key components by importance
    scored = [n for n in nodes if n["type"] in ("function", "class")
              and (n.get("semantics", {}).get("importance") or n.get("importance", 0))]
    scored.sort(key=lambda n: n.get("semantics", {}).get("importance", 0) or n.get("importance", 0), reverse=True)
    if scored:
        sections.append("\n## Key Components\n")
        for n in scored[:20]:
            sem = n.get("semantics", {})
            parts = [f"`{n['name']}`", f"({n['type']})"]
            role = sem.get("execution_role", "") or n.get("role", "")
            domain = sem.get("domain_hint", "") or n.get("domain", "")
            effects = [e.get("type", e) if isinstance(e, dict) else e for e in (sem.get("side_effects", []) or n.get("effects", []))]
            if role: parts.append(role)
            if domain: parts.append(f"[{domain}]")
            if effects: parts.append("→ " + ", ".join(effects[:3]))
            parts.append(f"in `{n.get('file_path', '')}`")
            sections.append(f"- {' · '.join(parts)}")
        sections.append("")

    # Complexity hotspots
    complex_nodes = [n for n in nodes if n.get("complexity") == "complex" and n["type"] in ("function", "class")]
    complex_nodes.sort(key=lambda n: (n.get("line_range", [0, 0])[1] - n.get("line_range", [0, 0])[0]), reverse=True)
    if complex_nodes:
        sections.append("\n## Complexity Hotspots\n")
        for n in complex_nodes[:15]:
            lr = n.get("line_range", [0, 0])
            lines = lr[1] - lr[0] + 1 if lr[1] > lr[0] else 0
            sections.append(f"- `{n['name']}` ({lines} lines) in `{n.get('file_path', '')}`")
        sections.append("")

    # Reading order by layer dependency
    layer_order = ["Data / Storage", "Service / Logic", "API / Routes", "UI / Frontend", "Infrastructure", "Tests"]
    ordered = [l for lo in layer_order for l in layers if l["name"] == lo]
    if ordered:
        sections.append("\n## Recommended Reading Order\n")
        for i, l in enumerate(ordered, 1):
            file_nodes = [n for n in nodes if n["id"] in set(l["node_ids"]) and n["type"] == "file"]
            dirs = sorted(set(str(Path(n["file_path"]).parent) for n in file_nodes[:50]))[:5]
            sections.append(f"{i}. **{l['name']}** — {', '.join(dirs) if dirs else 'various'}")
        sections.append("")

    # ─── Flow Analysis ─────────────────────────────────────────────────────
    node_map = {n["id"]: n for n in nodes}
    calls_from = defaultdict(list)
    for e in edges:
        if e["type"] == "calls" and e["source"] in node_map and e["target"] in node_map:
            calls_from[e["source"]].append(e["target"])

    def _get_role(n):
        return (n.get("semantics", {}).get("execution_role", "") or n.get("role", ""))
    def _get_effects(n):
        return [e.get("type", e) if isinstance(e, dict) else e for e in (n.get("semantics", {}).get("side_effects", []) or n.get("effects", []))]
    def _trace(start_id, max_depth=6):
        chain, visited = [], set()
        def walk(nid, depth):
            if nid in visited or depth > max_depth: return
            visited.add(nid); chain.append(nid)
            for t in calls_from.get(nid, [])[:3]:
                if t not in visited: walk(t, depth + 1)
        walk(start_id, 0)
        return chain

    # API Call Flows: entry_point → ... → external_api
    api_entries = [n for n in nodes if n["type"] in ("function", "class") and _get_role(n) == "entry_point"]
    api_flows = []
    for entry in api_entries[:15]:
        chain = _trace(entry["id"])
        chain_nodes = [node_map[nid] for nid in chain if nid in node_map]
        has_api = any("external_api" in str(_get_effects(cn)) for cn in chain_nodes)
        if has_api and len(chain_nodes) >= 2:
            api_flows.append(chain_nodes)
    if api_flows:
        sections.append("\n## API Call Flows\n")
        for flow in api_flows[:8]:
            arrow = " → ".join(f"`{n['name']}`" for n in flow[:6])
            effects = set()
            for n in flow:
                for e in _get_effects(n):
                    if "external_api" in e: effects.add(e)
            sections.append(f"- {arrow}" + (f" ({', '.join(effects)})" if effects else ""))
        sections.append("")

    # Data Flows: functions that write DB, traced from callers
    db_writers = [n for n in nodes if n["type"] in ("function", "class") and any("db_write" in str(e) for e in _get_effects(n))]
    if db_writers:
        sections.append("\n## Data Flows\n")
        sections.append("Functions that write to database and their call chains:\n")
        shown = set()
        for writer in db_writers[:15]:
            # Find callers
            callers = [node_map[e["source"]]["name"] for e in edges
                       if e["target"] == writer["id"] and e["type"] == "calls" and e["source"] in node_map]
            key = writer["name"]
            if key in shown: continue
            shown.add(key)
            tables = [e for e in _get_effects(writer) if "db_write" in e]
            caller_str = f" ← called by {', '.join(f'`{c}`' for c in callers[:3])}" if callers else ""
            sections.append(f"- `{writer['name']}` ({', '.join(tables)}){caller_str}")
        sections.append("")

    # Screen/Route Flows: UI/API layer → Service → Data
    layer_map = {}
    for l in layers:
        for nid in l["node_ids"]: layer_map[nid] = l["name"]
    api_nodes = [n for n in nodes if n["type"] in ("function", "class") and layer_map.get(n["id"]) in ("API / Routes", "UI / Frontend")]
    route_flows = []
    for entry in api_nodes[:20]:
        chain = _trace(entry["id"])
        if len(chain) < 2: continue
        chain_nodes = [node_map[nid] for nid in chain if nid in node_map]
        layers_hit = list(dict.fromkeys(layer_map.get(nid, "") for nid in chain if layer_map.get(nid)))
        if len(layers_hit) >= 2:
            route_flows.append((chain_nodes, layers_hit))
    if route_flows:
        sections.append("\n## Request Flows (Route → Service → Data)\n")
        for flow, flow_layers in route_flows[:10]:
            arrow = " → ".join(f"`{n['name']}`" for n in flow[:5])
            sections.append(f"- {arrow}")
            sections.append(f"  Layers: {' → '.join(flow_layers)}")
        sections.append("")

    # Write
    content = "\n".join(sections)
    out_path = root / output
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(content, encoding="utf-8")
    return str(out_path.relative_to(root))
