"""Onboarding guide generator — create docs/ONBOARDING.md from knowledge graph."""

from pathlib import Path
from collections import defaultdict
from typing import List


def generate_onboard(graph_data: dict, root: Path, output: str = "docs/ONBOARDING.md") -> str:
    """Generate onboarding markdown from graph data. Returns file path."""
    p = graph_data["project"]
    nodes = graph_data["nodes"]
    edges = graph_data.get("edges", [])
    layers = graph_data.get("layers", [])

    sections = [f"# {p['name']} — Onboarding Guide\n", "Auto-generated by SteerCode.\n"]
    sections.append(_section_overview(p, nodes))
    sections.append(_section_layers(layers))
    sections.append(_section_key_components(nodes))
    sections.append(_section_hotspots(nodes))
    sections.append(_section_reading_order(nodes, layers))

    # Flow sections
    node_map = {n["id"]: n for n in nodes}
    calls_from = _build_calls_map(edges, node_map)
    layer_map = _build_layer_map(layers)

    sections.append(_section_api_flows(nodes, node_map, calls_from))
    sections.append(_section_data_flows(nodes, edges, node_map))
    sections.append(_section_request_flows(nodes, node_map, calls_from, layer_map))

    content = "\n".join(s for s in sections if s)
    out_path = root / output
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(content, encoding="utf-8")
    return str(out_path.relative_to(root))


# ─── Helpers ─────────────────────────────────────────────────────────────────

def _get_role(n):
    return n.get("semantics", {}).get("execution_role", "") or n.get("role", "")

def _get_effects(n):
    return [e.get("type", e) if isinstance(e, dict) else e
            for e in (n.get("semantics", {}).get("side_effects", []) or n.get("effects", []))]

def _get_domain(n):
    return n.get("semantics", {}).get("domain_hint", "") or n.get("domain", "")

def _build_calls_map(edges, node_map):
    calls_from = defaultdict(list)
    for e in edges:
        if e["type"] == "calls" and e["source"] in node_map and e["target"] in node_map:
            calls_from[e["source"]].append(e["target"])
    return calls_from

def _build_layer_map(layers):
    m = {}
    for l in layers:
        for nid in l["node_ids"]: m[nid] = l["name"]
    return m

def _trace(start_id, calls_from, visited=None, max_depth=6):
    chain, visited = [], visited or set()
    def walk(nid, depth):
        if nid in visited or depth > max_depth: return
        visited.add(nid); chain.append(nid)
        for t in calls_from.get(nid, [])[:3]:
            if t not in visited: walk(t, depth + 1)
    walk(start_id, 0)
    return chain


# ─── Sections ────────────────────────────────────────────────────────────────

def _section_overview(p, nodes):
    counts = defaultdict(int)
    for n in nodes: counts[n["type"]] += 1
    versions = p.get("versions", {})
    fw = ", ".join(f"{k} {v}" for k, v in versions.get("frameworks", {}).items()) or "—"
    return f"""
## Overview

| Metric | Value |
|---|---|
| Languages | {', '.join(p.get('languages', [])[:8])} |
| Files | {counts.get('file', 0):,} |
| Functions | {counts.get('function', 0):,} |
| Classes | {counts.get('class', 0):,} |
| Frameworks | {fw} |
"""


def _section_layers(layers):
    if not layers: return ""
    lines = ["## Architecture\n"]
    for l in sorted(layers, key=lambda x: -len(x["node_ids"])):
        lines.append(f"- **{l['name']}** ({len(l['node_ids']):,} nodes)")
    return "\n".join(lines) + "\n"


def _section_key_components(nodes):
    scored = [n for n in nodes if n["type"] in ("function", "class")
              and (n.get("semantics", {}).get("importance") or n.get("importance", 0))]
    scored.sort(key=lambda n: n.get("semantics", {}).get("importance", 0) or n.get("importance", 0), reverse=True)
    if not scored: return ""
    lines = ["\n## Key Components\n"]
    for n in scored[:20]:
        parts = [f"`{n['name']}`", f"({n['type']})"]
        role, domain = _get_role(n), _get_domain(n)
        effects = _get_effects(n)
        if role: parts.append(role)
        if domain: parts.append(f"[{domain}]")
        if effects: parts.append("→ " + ", ".join(effects[:3]))
        parts.append(f"in `{n.get('file_path', '')}`")
        lines.append(f"- {' · '.join(parts)}")
    return "\n".join(lines) + "\n"


def _section_hotspots(nodes):
    complex_nodes = sorted(
        [n for n in nodes if n.get("complexity") == "complex" and n["type"] in ("function", "class")],
        key=lambda n: (n.get("line_range", [0, 0])[1] - n.get("line_range", [0, 0])[0]), reverse=True)
    if not complex_nodes: return ""
    lines = ["\n## Complexity Hotspots\n"]
    for n in complex_nodes[:15]:
        lr = n.get("line_range", [0, 0])
        loc = lr[1] - lr[0] + 1 if lr[1] > lr[0] else 0
        lines.append(f"- `{n['name']}` ({loc} lines) in `{n.get('file_path', '')}`")
    return "\n".join(lines) + "\n"


def _section_reading_order(nodes, layers):
    order = ["Data / Storage", "Service / Logic", "API / Routes", "UI / Frontend", "Infrastructure", "Tests"]
    ordered = [l for lo in order for l in layers if l["name"] == lo]
    if not ordered: return ""
    node_set = {n["id"]: n for n in nodes}
    lines = ["\n## Recommended Reading Order\n"]
    for i, l in enumerate(ordered, 1):
        file_nodes = [node_set[nid] for nid in l["node_ids"] if nid in node_set and node_set[nid]["type"] == "file"]
        dirs = sorted(set(str(Path(n["file_path"]).parent) for n in file_nodes[:50]))[:5]
        lines.append(f"{i}. **{l['name']}** — {', '.join(dirs) if dirs else 'various'}")
    return "\n".join(lines) + "\n"


def _section_api_flows(nodes, node_map, calls_from):
    entries = [n for n in nodes if n["type"] in ("function", "class") and _get_role(n) == "entry_point"]
    flows = []
    for entry in entries[:15]:
        chain = _trace(entry["id"], calls_from)
        chain_nodes = [node_map[nid] for nid in chain if nid in node_map]
        if any("external_api" in str(_get_effects(cn)) for cn in chain_nodes) and len(chain_nodes) >= 2:
            flows.append(chain_nodes)
    if not flows: return ""
    lines = ["\n## API Call Flows\n"]
    for flow in flows[:8]:
        arrow = " → ".join(f"`{n['name']}`" for n in flow[:6])
        effects = {e for n in flow for e in _get_effects(n) if "external_api" in e}
        lines.append(f"- {arrow}" + (f" ({', '.join(effects)})" if effects else ""))
    return "\n".join(lines) + "\n"


def _section_data_flows(nodes, edges, node_map):
    writers = [n for n in nodes if n["type"] in ("function", "class") and any("db_write" in str(e) for e in _get_effects(n))]
    if not writers: return ""
    lines = ["\n## Data Flows\n", "Functions that write to database and their call chains:\n"]
    shown = set()
    for w in writers[:15]:
        if w["name"] in shown: continue
        shown.add(w["name"])
        callers = [node_map[e["source"]]["name"] for e in edges
                   if e["target"] == w["id"] and e["type"] == "calls" and e["source"] in node_map]
        tables = [e for e in _get_effects(w) if "db_write" in e]
        caller_str = f" ← called by {', '.join(f'`{c}`' for c in callers[:3])}" if callers else ""
        lines.append(f"- `{w['name']}` ({', '.join(tables)}){caller_str}")
    return "\n".join(lines) + "\n"


def _section_request_flows(nodes, node_map, calls_from, layer_map):
    api_nodes = [n for n in nodes if n["type"] in ("function", "class")
                 and layer_map.get(n["id"]) in ("API / Routes", "UI / Frontend")]
    flows = []
    for entry in api_nodes[:20]:
        chain = _trace(entry["id"], calls_from)
        if len(chain) < 2: continue
        layers_hit = list(dict.fromkeys(layer_map.get(nid, "") for nid in chain if layer_map.get(nid)))
        if len(layers_hit) >= 2:
            flows.append(([node_map[nid] for nid in chain if nid in node_map], layers_hit))
    if not flows: return ""
    lines = ["\n## Request Flows (Route → Service → Data)\n"]
    for flow, flow_layers in flows[:10]:
        lines.append("- " + " → ".join(f"`{n['name']}`" for n in flow[:5]))
        lines.append(f"  Layers: {' → '.join(flow_layers)}")
    return "\n".join(lines) + "\n"
